[package]
name = "eldiro"
author = "Luke O'Malley <luke@lukeomalley.xyz>"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
